### ISSUE TITLE
Vehicle Terminal. 

### ISSUE THREAD

**Issue by Scarecrow631** [Kellojo/ETG-Wave-Defense#1]
Is it only meant for selling Vehicles?

Would it be possible to get vehicle spawns for the players?

**Comment by Kellojo** [comment]
It is only meant for selling vehicles.
I have not thought about the possibility of buying them because it seemed more interesting of a mechanic if the players would have to capture/steal them.

**Comment by Scarecrow631** [comment]
That's a fair point, far more enjoyable to steal them.
